/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fenetre;

import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author 33768
 */
public class AjoutArticle extends javax.swing.JFrame {

    private String mailAdress;
    private int mois;
    private int annee;
    private int jour;
    private int heure;
    private int minute;
    private int seconde;
    /**
     * Creates new form AjoutArticle
     */
    public AjoutArticle() {
        initComponents();
        dateHeure();
    }
    
    public AjoutArticle(String adresseMail)
    {
        initComponents();
        this.mailAdress = adresseMail;
        dateHeure();
    }
    
    public String getMailAdress() {
        return this.mailAdress;
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void connexion() {
        try {
            //maconnexion= new Connexion("shopping","root","");
            Class.forName("com.mysql.cj.jdbc.Driver");

            //nameDatabase="shopping";  //nom de la database sur wampserveur
            String urlDatabase = "jdbc:mysql://localhost:3306/shopping";

            //création d'une connexion JDBC à la base 
            con = DriverManager.getConnection(urlDatabase,"root", "root");
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
             // sous programme pour avoir la date actuelle et l'heure actuelle
    public void dateHeure() {
        Thread tr = new Thread() {
            @Override
            public void run() {
                for (;;) {
                    try {
                        Calendar calendrier = new GregorianCalendar();

                        annee = calendrier.get(Calendar.YEAR);
                        mois = calendrier.get(Calendar.MONTH);
                        jour = calendrier.get(Calendar.DAY_OF_MONTH);

                        heure = calendrier.get(Calendar.HOUR_OF_DAY);
                        minute = calendrier.get(Calendar.MINUTE);
                        seconde = calendrier.get(Calendar.SECOND);

                        mois = mois + 1;
                        textDate.setText(jour + "/" + mois + "/" + annee);
                        textHeure.setText(heure + ":" + minute + ":" + seconde);
                        sleep(1000);

                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }

        };
        tr.start();

    }
    
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonDeco = new javax.swing.JButton();
        textDate = new javax.swing.JLabel();
        textHeure = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textMarque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textPrixUnit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textPrixPack = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textQuantitePack = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textStock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textDescription = new javax.swing.JTextField();
        buttonAjout = new javax.swing.JButton();
        buttonRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabel1.setText("Ajouter un article");

        buttonDeco.setBackground(new java.awt.Color(0, 0, 0));
        buttonDeco.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        buttonDeco.setForeground(new java.awt.Color(255, 255, 255));
        buttonDeco.setText("SE DECONNECTER");
        buttonDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecoActionPerformed(evt);
            }
        });

        textDate.setText("DATE");

        textHeure.setText("HEURE");

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel2.setText("Nom de la marque :");

        textMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMarqueActionPerformed(evt);
            }
        });
        textMarque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMarqueKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel3.setText("Prix unitaire :");

        textPrixUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPrixUnitKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel4.setText("Prix Pack :");

        textPrixPack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPrixPackKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel5.setText("Quantité Pack : ");

        textQuantitePack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textQuantitePackKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel6.setText("Stock : ");

        textStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textStockKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel7.setText("Description :");

        textDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textDescriptionKeyPressed(evt);
            }
        });

        buttonAjout.setBackground(new java.awt.Color(0, 0, 0));
        buttonAjout.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        buttonAjout.setForeground(new java.awt.Color(255, 255, 255));
        buttonAjout.setText("Ajouter l'article");
        buttonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjoutActionPerformed(evt);
            }
        });

        buttonRetour.setBackground(new java.awt.Color(0, 0, 0));
        buttonRetour.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        buttonRetour.setForeground(new java.awt.Color(255, 255, 255));
        buttonRetour.setText("Retour");
        buttonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(textDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textHeure)
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(buttonDeco, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textMarque)
                                    .addComponent(textPrixUnit)
                                    .addComponent(textPrixPack)
                                    .addComponent(textQuantitePack)
                                    .addComponent(textStock)
                                    .addComponent(textDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonRetour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(buttonDeco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDate)
                            .addComponent(textHeure))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPrixUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPrixPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textQuantitePack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAjout)
                    .addComponent(buttonRetour))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecoActionPerformed
        // TODO add your handling code here:
        AjoutArticle.super.dispose();
        connexion();

        Home homepage = new Home();
        homepage.setVisible(true);
    }//GEN-LAST:event_buttonDecoActionPerformed

    private void textMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMarqueActionPerformed

    private void buttonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjoutActionPerformed
        // TODO add your handling code here:
         try{
          connexion();  
          String dataMarque=textMarque.getText(); 
          String dataPrixUnit=textPrixUnit.getText();
          String dataPrixPack=textPrixPack.getText();
          String dataQuantitePack=textQuantitePack.getText();
          String dataStock=textStock.getText();
          String dataDescription=textDescription.getText();
          
          String requeteInsertionArticle="INSERT INTO article(marque,prix_unitaire,prix_pack,Quantite_pack,reference,stock,description) VALUES(?,?,?,?,NULL,?,?)";
          
          pst=con.prepareStatement(requeteInsertionArticle);
          pst.setString(1,dataMarque);
          pst.setString(2,dataPrixUnit);
          pst.setString(3,dataPrixPack);
          pst.setString(4,dataQuantitePack);
          pst.setString(5,dataStock);
          pst.setString(6,dataDescription);
          int row=pst.executeUpdate();
          
           JOptionPane.showMessageDialog(null,"Votre article a été créé avec succès");
        }catch(Exception e)
        {
            e.printStackTrace();
        }
         
    }//GEN-LAST:event_buttonAjoutActionPerformed

    private void buttonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetourActionPerformed
        // TODO add your handling code here:
        AjoutArticle.super.dispose();
        connexion();

        //PageEmpConnecte retourPageEmp = new PageEmpConnecte(getMailAdress());
        PageEmpConnecte retourPageEmp = new PageEmpConnecte(getMailAdress());
        retourPageEmp.setVisible(true);
        
    }//GEN-LAST:event_buttonRetourActionPerformed

    
    
    private void textMarqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMarqueKeyPressed
        // TODO add your handling code here:
         String marque=textMarque.getText();
        
        int tailleMarque=marque.length();
        
            if(tailleMarque<30){
                textMarque.setEditable(true);
            }else
            {
                  if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textMarque.setEditable(true);
           }else
           {
               textMarque.setEditable(false);
           }
            }
    }//GEN-LAST:event_textMarqueKeyPressed

    private void textPrixUnitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrixUnitKeyPressed
        // TODO add your handling code here:
        String prixUnit=textPrixUnit.getText();
        
        int taillePrixUnit=prixUnit.length();
        
        char verifPrixUnit=evt.getKeyChar();
        
        if((verifPrixUnit>='0') && (verifPrixUnit<='9'))
        {
            if(taillePrixUnit<4){
                textPrixUnit.setEditable(true);
            }else
            {
                textPrixUnit.setEditable(false);
            }
        }else
        {
           if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textPrixUnit.setEditable(true);
           }else
           {
               textPrixUnit.setEditable(false);
           }
        }
    }//GEN-LAST:event_textPrixUnitKeyPressed

    private void textPrixPackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrixPackKeyPressed
        // TODO add your handling code here:
        String prixPack=textPrixPack.getText();
        
        int taillePrixPack=prixPack.length();
        
        char verifPrixPack=evt.getKeyChar();
        
        if((verifPrixPack>='0') && (verifPrixPack<='9'))
        {
            if(taillePrixPack<4){
                textPrixPack.setEditable(true);
            }else
            {
                textPrixPack.setEditable(false);
            }
        }else
        {
           if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textPrixPack.setEditable(true);
           }else
           {
               textPrixPack.setEditable(false);
           }
        }
    }//GEN-LAST:event_textPrixPackKeyPressed

    private void textQuantitePackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textQuantitePackKeyPressed
        // TODO add your handling code here:
        String quantitePack=textQuantitePack.getText();
        
        int tailleQuantitePack=quantitePack.length();
        
        char verifQuantitePack=evt.getKeyChar();
        
        if((verifQuantitePack>='0') && (verifQuantitePack<='9'))
        {
            if(tailleQuantitePack<4){
                textQuantitePack.setEditable(true);
            }else
            {
                textQuantitePack.setEditable(false);
            }
        }else
        {
           if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textQuantitePack.setEditable(true);
           }else
           {
               textQuantitePack.setEditable(false);
           }
        }
    }//GEN-LAST:event_textQuantitePackKeyPressed

    private void textStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textStockKeyPressed
        // TODO add your handling code here:
        String stock=textStock.getText();
        
        int tailleStock=stock.length();
        
        char verifStock=evt.getKeyChar();
        
        if((verifStock>='0') && (verifStock<='9'))
        {
            if(tailleStock<4){
                textStock.setEditable(true);
            }else
            {
                textStock.setEditable(false);
            }
        }else
        {
           if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textStock.setEditable(true);
           }else
           {
               textStock.setEditable(false);
           }
        }
    }//GEN-LAST:event_textStockKeyPressed

    private void textDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDescriptionKeyPressed
        // TODO add your handling code here:
        String description=textDescription.getText();
        
        int tailleDescription=description.length();
        
            if(tailleDescription<100){
                textDescription.setEditable(true);
            }else
            {
                  if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textDescription.setEditable(true);
           }else
           {
               textDescription.setEditable(false);
           }
            }
    }//GEN-LAST:event_textDescriptionKeyPressed

    
    
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutArticle(getMailAdress()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjout;
    private javax.swing.JButton buttonDeco;
    private javax.swing.JButton buttonRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textDate;
    private javax.swing.JTextField textDescription;
    private javax.swing.JLabel textHeure;
    private javax.swing.JTextField textMarque;
    private javax.swing.JTextField textPrixPack;
    private javax.swing.JTextField textPrixUnit;
    private javax.swing.JTextField textQuantitePack;
    private javax.swing.JTextField textStock;
    // End of variables declaration//GEN-END:variables
}
