/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fenetre;

import Connexion.*;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 33768
 */
public class PageCreationCompteEmploye extends javax.swing.JFrame {

    /**
     * Creates new form PageCreationCompteEmploye
     */
    public PageCreationCompteEmploye() {
        initComponents();
    }
    
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public void connexionEmploye()
    {
        try{
            //maconnexion= new Connexion("shopping","root","");
          Class.forName("com.mysql.cj.jdbc.Driver");
        
        //nameDatabase="shopping";  //nom de la database sur wampserveur
        String urlDatabase="jdbc:mysql://localhost:3306/shopping";
        
        //création d'une connexion JDBC à la base 
          con=DriverManager.getConnection(urlDatabase,"root","");
        }catch(Exception e)
        {
               e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNomEmploye = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textPrenomEmploye = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textTelEmploye = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textNumVoieEmploye = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textAdresseEmploye = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textVilleEmploye = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textPaysEmploye = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textMailEmploye = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textMdpEmploye = new javax.swing.JTextField();
        buttonCreerEmploye = new javax.swing.JButton();
        comboboxSexeEmploye = new javax.swing.JComboBox<>();
        buttonRetourCoEmploye = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Création de votre Compte Employé");

        jLabel2.setText("Votre nom :");

        textNomEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomEmployeActionPerformed(evt);
            }
        });
        textNomEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNomEmployeKeyPressed(evt);
            }
        });

        jLabel3.setText("Votre prénom :");

        textPrenomEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrenomEmployeActionPerformed(evt);
            }
        });
        textPrenomEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPrenomEmployeKeyPressed(evt);
            }
        });

        jLabel4.setText("Sexe :");

        jLabel5.setText("Votre numéro de téléphone : ");

        textTelEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textTelEmployeKeyPressed(evt);
            }
        });

        jLabel6.setText("Votre numéro de voie :");

        textNumVoieEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumVoieEmployeActionPerformed(evt);
            }
        });
        textNumVoieEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNumVoieEmployeKeyPressed(evt);
            }
        });

        jLabel7.setText("Votre adresse :");

        textAdresseEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAdresseEmployeActionPerformed(evt);
            }
        });
        textAdresseEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textAdresseEmployeKeyPressed(evt);
            }
        });

        jLabel8.setText("Votre ville :");

        textVilleEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textVilleEmployeActionPerformed(evt);
            }
        });
        textVilleEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textVilleEmployeKeyPressed(evt);
            }
        });

        jLabel9.setText("Votre pays :");

        textPaysEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPaysEmployeActionPerformed(evt);
            }
        });
        textPaysEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPaysEmployeKeyPressed(evt);
            }
        });

        jLabel10.setText("Votre adresse mail :");

        textMailEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMailEmployeActionPerformed(evt);
            }
        });
        textMailEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMailEmployeKeyPressed(evt);
            }
        });

        jLabel11.setText("Votre mot de passe :");

        textMdpEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMdpEmployeActionPerformed(evt);
            }
        });
        textMdpEmploye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMdpEmployeKeyPressed(evt);
            }
        });

        buttonCreerEmploye.setBackground(new java.awt.Color(255, 0, 0));
        buttonCreerEmploye.setText("CREER VOTRE COMPTE");
        buttonCreerEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreerEmployeActionPerformed(evt);
            }
        });

        comboboxSexeEmploye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme", "Autres" }));
        comboboxSexeEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxSexeEmployeActionPerformed(evt);
            }
        });

        buttonRetourCoEmploye.setText("Retour");
        buttonRetourCoEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetourCoEmployeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(buttonRetourCoEmploye)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCreerEmploye)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel2))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNomEmploye)
                            .addComponent(textPrenomEmploye)
                            .addComponent(textTelEmploye)
                            .addComponent(textNumVoieEmploye)
                            .addComponent(textAdresseEmploye)
                            .addComponent(textVilleEmploye)
                            .addComponent(textPaysEmploye)
                            .addComponent(textMailEmploye)
                            .addComponent(textMdpEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(comboboxSexeEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNomEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPrenomEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboboxSexeEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTelEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textMailEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textNumVoieEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textAdresseEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textVilleEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textPaysEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMdpEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreerEmploye)
                    .addComponent(buttonRetourCoEmploye))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomEmployeActionPerformed

    private void textPrenomEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrenomEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrenomEmployeActionPerformed

    private void textNumVoieEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumVoieEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumVoieEmployeActionPerformed

    private void textVilleEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textVilleEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textVilleEmployeActionPerformed

    private void textPaysEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPaysEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPaysEmployeActionPerformed

    private void textAdresseEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAdresseEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAdresseEmployeActionPerformed

    private void textMailEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMailEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMailEmployeActionPerformed

    private void textMdpEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMdpEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMdpEmployeActionPerformed

    private void comboboxSexeEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxSexeEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxSexeEmployeActionPerformed

    private void buttonCreerEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreerEmployeActionPerformed
       try{
        connexionEmploye();
        
        //blindage des saisies dans la page de création
        if((textNomEmploye.getText().length()==0)||(textPrenomEmploye.getText().length()==0)||(textTelEmploye.getText().length()==0)||(textMailEmploye.getText().length()==0)||(textNumVoieEmploye.getText().length()==0)||(textAdresseEmploye.getText().length()==0)||(textVilleEmploye.getText().length()==0)||(textPaysEmploye.getText().length()==0)||(textMdpEmploye.getText().length()==0))
        {
         JOptionPane.showMessageDialog(null,"Vous n'avez pas rempli entièrement les informations");
 
        }else
        {
            
        pst=con.prepareStatement("INSERT INTO employe(id_employe,employe_nom,employe_prenom,employe_sexe,employe_tel,employe_mail,employe_num_voie,employe_adresse,employe_ville,employe_pays,employe_mdp) VALUES(NULL,?,?,?,?,?,?,?,?,?,?)");  //requête de création compte employé
        pst.setString(1,textNomEmploye.getText().toUpperCase());
        pst.setString(2,textPrenomEmploye.getText().toUpperCase());
        pst.setString(3,comboboxSexeEmploye.getSelectedItem().toString().toUpperCase());
        pst.setString(4,textTelEmploye.getText());
        pst.setString(5,textMailEmploye.getText());
        pst.setString(6,textNumVoieEmploye.getText());
        pst.setString(7,textAdresseEmploye.getText().toUpperCase());
        pst.setString(8,textVilleEmploye.getText().toUpperCase());
        pst.setString(9,textPaysEmploye.getText().toUpperCase());
        pst.setString(10,textMdpEmploye.getText());
        int row=pst.executeUpdate();
        
        int numero_de_tel_employe=Integer.parseInt(String.valueOf(textTelEmploye.getText()));
        int num_voie_employe=Integer.parseInt(String.valueOf(textNumVoieEmploye.getText()));
        myEmploye=new Employe(textNomEmploye.getText().toUpperCase(),textPrenomEmploye.getText().toUpperCase(),numero_de_tel_employe,textMailEmploye.getText(),num_voie_employe,textAdresseEmploye.getText().toUpperCase(),textVilleEmploye.getText().toUpperCase(),textPaysEmploye.getText().toUpperCase(),textMdpEmploye.getText().toUpperCase());
        myEmploye.toString();
        JOptionPane.showMessageDialog(null,"Votre compte a été créé avec succès");
        }
        
       }catch(SQLException e)
       {
           e.printStackTrace();
       }
        
        
    }//GEN-LAST:event_buttonCreerEmployeActionPerformed

    private void buttonRetourCoEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetourCoEmployeActionPerformed
        // TODO add your handling code here:
        PageConnexionEmploye coEmploye=new PageConnexionEmploye();
        coEmploye.setVisible(true);
    }//GEN-LAST:event_buttonRetourCoEmployeActionPerformed

    private void textNomEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNomEmployeKeyPressed
        // TODO add your handling code here:
          String nom=textNomEmploye.getText();
        
        int tailleNom=nom.length();
        
        char verifNom=evt.getKeyChar();
        
            if(tailleNom<30){
                
               if((verifNom>='0') && (verifNom<='9'))
                {
                textNomEmploye.setEditable(false);
                }else
               {
                   textNomEmploye.setEditable(true);
               }
               
            }else
            {     
        
           if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textNomEmploye.setEditable(true);
           }else
           {
               textNomEmploye.setEditable(false);
           }
        }
             
    }//GEN-LAST:event_textNomEmployeKeyPressed

    private void textPrenomEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrenomEmployeKeyPressed
        // TODO add your handling code here:
         String prenom=textPrenomEmploye.getText();
        
        int taillePrenom=prenom.length();
        
            if(taillePrenom<30){
                textPrenomEmploye.setEditable(true);
            }else
            {
                  if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textPrenomEmploye.setEditable(true);
           }else
           {
               textPrenomEmploye.setEditable(false);
           }
            }
    }//GEN-LAST:event_textPrenomEmployeKeyPressed

    private void textTelEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelEmployeKeyPressed
        // TODO add your handling code here:
         String numTel=textTelEmploye.getText();
        
        int tailleNumTel=numTel.length();
        
        char verifNum=evt.getKeyChar();
        
        if((verifNum>='0') && (verifNum<='9'))
        {
            if(tailleNumTel<10){
                textTelEmploye.setEditable(true);
            }else
            {
                textTelEmploye.setEditable(false);
            }
        }else
        {
           if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textTelEmploye.setEditable(true);
           }else
           {
               textTelEmploye.setEditable(false);
           }
        }
    }//GEN-LAST:event_textTelEmployeKeyPressed

    private void textMailEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMailEmployeKeyPressed
        // TODO add your handling code here:
        String mail=textMailEmploye.getText();
        
        int tailleMail=mail.length();
        
            if(tailleMail<50){
                textMailEmploye.setEditable(true);
            }else
            {
                  if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textMailEmploye.setEditable(true);
           }else
           {
               textMailEmploye.setEditable(false);
           }
            }
        
    }//GEN-LAST:event_textMailEmployeKeyPressed

    private void textNumVoieEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumVoieEmployeKeyPressed
        // TODO add your handling code here:
        String numVoie=textNumVoieEmploye.getText();
        
        int tailleNumVoie=numVoie.length();
        
        char verifNumVoie=evt.getKeyChar();
        
        if((verifNumVoie>='0') && (verifNumVoie<='9'))
        {
            if(tailleNumVoie<4){
                textNumVoieEmploye.setEditable(true);
            }else
            {
                textNumVoieEmploye.setEditable(false);
            }
        }else
        {
           if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textNumVoieEmploye.setEditable(true);
           }else
           {
               textNumVoieEmploye.setEditable(false);
           }
        }
    }//GEN-LAST:event_textNumVoieEmployeKeyPressed

    private void textAdresseEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAdresseEmployeKeyPressed
        // TODO add your handling code here:
         String adresse=textAdresseEmploye.getText();
        
        int tailleAdresse=adresse.length();
        
        char verifAdresse=evt.getKeyChar();
        
            if(tailleAdresse<50){
                
               if((verifAdresse>='0') && (verifAdresse<='9'))
                {
                textAdresseEmploye.setEditable(false);
                }else
               {
                   textAdresseEmploye.setEditable(true);
               }
               
            }else
            {
                  if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textAdresseEmploye.setEditable(true);
           }else
           {
               textAdresseEmploye.setEditable(false);
           }
            }
        
    }//GEN-LAST:event_textAdresseEmployeKeyPressed

    private void textVilleEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textVilleEmployeKeyPressed
        // TODO add your handling code here:
        String ville=textVilleEmploye.getText();
        
        int tailleVille=ville.length();
        
        char verifVille=evt.getKeyChar();
        
            if(tailleVille<30){
                
               if((verifVille>='0') && (verifVille<='9'))
                {
                textVilleEmploye.setEditable(false);
                }else
               {
                   textVilleEmploye.setEditable(true);
               }
               
            }else
            {
                  if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textVilleEmploye.setEditable(true);
           }else
           {
               textVilleEmploye.setEditable(false);
           }
            }
    }//GEN-LAST:event_textVilleEmployeKeyPressed

    private void textPaysEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPaysEmployeKeyPressed
        // TODO add your handling code here:
         String pays=textPaysEmploye.getText();
        
        int taillePays=pays.length();
        
        char verifPays=evt.getKeyChar();
        
            if(taillePays<30){
                
               if((verifPays>='0') && (verifPays<='9'))
                {
                textPaysEmploye.setEditable(false);
                }else
               {
                   textPaysEmploye.setEditable(true);
               }
               
            }else
            {
                  if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textPaysEmploye.setEditable(true);
           }else
           {
               textPaysEmploye.setEditable(false);
           }
            }
    }//GEN-LAST:event_textPaysEmployeKeyPressed

    private void textMdpEmployeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMdpEmployeKeyPressed
        // TODO add your handling code here:
          String mdp=textMdpEmploye.getText();
        
        int tailleMdp=mdp.length();
        
            if(tailleMdp<12){
                textMdpEmploye.setEditable(true);
            }else
            {
                 if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||evt.getExtendedKeyCode()==KeyEvent.VK_TAB) 
           {
               textMdpEmploye.setEditable(true);
           }else
           {
               textMdpEmploye.setEditable(false);
           }
            }
    }//GEN-LAST:event_textMdpEmployeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageCreationCompteEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageCreationCompteEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageCreationCompteEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageCreationCompteEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageCreationCompteEmploye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreerEmploye;
    private javax.swing.JButton buttonRetourCoEmploye;
    private javax.swing.JComboBox<String> comboboxSexeEmploye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textAdresseEmploye;
    private javax.swing.JTextField textMailEmploye;
    private javax.swing.JTextField textMdpEmploye;
    private javax.swing.JTextField textNomEmploye;
    private javax.swing.JTextField textNumVoieEmploye;
    private javax.swing.JTextField textPaysEmploye;
    private javax.swing.JTextField textPrenomEmploye;
    private javax.swing.JTextField textTelEmploye;
    private javax.swing.JTextField textVilleEmploye;
    // End of variables declaration//GEN-END:variables

    private Employe myEmploye;
}
