/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fenetre;

import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class RechercheClient extends javax.swing.JFrame {

     private String mailAdress;
    private int mois;
    private int annee;
    private int jour;
    private int heure;
    private int minute;
    private int seconde;
    /**
     * Creates new form RechercheClient
     */
    public RechercheClient() {
        initComponents();
        dateHeure();
    }

       public RechercheClient(String adresseMail) {
        initComponents();
          this.mailAdress = adresseMail;
        dateHeure();
    }
     public String getMailAdress() {
        return this.mailAdress;
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
     //.......CONNEXION BDD........
    
    public void connexion() {
        try {
            //maconnexion= new Connexion("shopping","root","");
            Class.forName("com.mysql.cj.jdbc.Driver");

            //nameDatabase="shopping";  //nom de la database sur wampserveur
            String urlDatabase = "jdbc:mysql://localhost:3306/shopping";

            //création d'une connexion JDBC à la base 
            con = DriverManager.getConnection(urlDatabase,"root", "root");
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        // sous programme pour avoir la date actuelle et l'heure actuelle
    public void dateHeure() {
        Thread tr = new Thread() {
            @Override
            public void run() {
                for (;;) {
                    try {
                        Calendar calendrier = new GregorianCalendar();

                        annee = calendrier.get(Calendar.YEAR);
                        mois = calendrier.get(Calendar.MONTH);
                        jour = calendrier.get(Calendar.DAY_OF_MONTH);

                        heure = calendrier.get(Calendar.HOUR_OF_DAY);
                        minute = calendrier.get(Calendar.MINUTE);
                        seconde = calendrier.get(Calendar.SECOND);

                        mois = mois + 1;
                        textDate.setText(jour + "/" + mois + "/" + annee);
                        textHeure.setText(heure + ":" + minute + ":" + seconde);
                        sleep(1000);

                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }

        };
        tr.start();

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonRetour = new javax.swing.JButton();
        textDate = new javax.swing.JLabel();
        textHeure = new javax.swing.JLabel();
        textRecherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabel1.setText("Recherche de clients");

        buttonRetour.setBackground(new java.awt.Color(0, 0, 0));
        buttonRetour.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        buttonRetour.setForeground(new java.awt.Color(255, 255, 255));
        buttonRetour.setText("Retour");
        buttonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetourActionPerformed(evt);
            }
        });

        textDate.setText("date");

        textHeure.setText("heure");

        textRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRechercheActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Afficher tous les clients");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(26);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(textDate)
                .addGap(18, 18, 18)
                .addComponent(textHeure)
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(buttonRetour)
                .addGap(36, 36, 36))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(textRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(buttonRetour)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDate)
                            .addComponent(textHeure))))
                .addGap(32, 32, 32)
                .addComponent(textRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRechercheActionPerformed
   
    }//GEN-LAST:event_textRechercheActionPerformed
  //.....APPUIE SUR RECHERCHE....
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          //..........AFFICHAGE BDD ARTICLE.........
       try{
            connexion();
          String v=textRecherche.getText(); //on récupère la valeur tapé 
          
            String client[]={"id_client","client_nom","client_prenom","client_tel","client_mail","client_num_voie","client_adresse","client_ville","client_pays"};
            String montrer[]= new String [9];
            
            DefaultTableModel model= new DefaultTableModel (null, client);
            
            //requête sql
            String sql= "SELECT * from client WHERE id_client='"+v+"' OR client_prenom='"+v+"' OR client_nom='"+v+"' OR client_tel='"+v+"' OR client_mail='"+v+"' OR client_num_voie='"+v+"' OR client_adresse='"+v+"' OR client_ville='"+v+"' OR client_pays='"+v+"'";
            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
         while(rs.next()) {
             montrer[0]= rs.getString("id_client");
             montrer[1]= rs.getString("client_nom");
             montrer[2]= rs.getString("client_prenom");
             montrer[3]= rs.getString("client_tel");
             montrer[4]= rs.getString("client_mail");
             montrer[5]= rs.getString("client_num_voie");
             montrer[6]= rs.getString("client_adresse");
             montrer[7]= rs.getString("client_ville");
             montrer[8]= rs.getString("client_pays");
             
             model.addRow(montrer);
             
         }
         jTable1.setModel(model);
         con.close();
        }catch(Exception e){
             e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

      //.....AFFICHE TOUTE LA BDD...
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
           connexion();
 
          
            String client[]={"id_client","client_nom","client_prenom","client_tel","client_mail","client_num_voie","client_adresse","client_ville","client_pays"};
            String montrer[]= new String [9];
            
            DefaultTableModel model= new DefaultTableModel (null, client);
            
            //requête sql
            String sql= "SELECT * from client";
            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
         while(rs.next()) {
             montrer[0]= rs.getString("id_client");
             montrer[1]= rs.getString("client_nom");
             montrer[2]= rs.getString("client_prenom");
             montrer[3]= rs.getString("client_tel");
             montrer[4]= rs.getString("client_mail");
             montrer[5]= rs.getString("client_num_voie");
             montrer[6]= rs.getString("client_adresse");
             montrer[7]= rs.getString("client_ville");
             montrer[8]= rs.getString("client_pays");
             
             model.addRow(montrer);
             
         }
         jTable1.setModel(model);
         con.close();
        }catch(Exception e){
             e.printStackTrace();
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetourActionPerformed
        RechercheClient.super.dispose();
        connexion();

        //PageEmpConnecte retourPageEmp = new PageEmpConnecte(getMailAdress());
        PageEmpConnecte retourPageEmp = new PageEmpConnecte(getMailAdress());
        retourPageEmp.setVisible(true);
    }//GEN-LAST:event_buttonRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercheClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRetour;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel textDate;
    private javax.swing.JLabel textHeure;
    private javax.swing.JTextField textRecherche;
    // End of variables declaration//GEN-END:variables
}
