/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fenetre;

import java.awt.HeadlessException;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author 33768
 */
public class SupprimerArticle extends javax.swing.JFrame {

    private String mailAdress;
    private int mois;
    private int annee;
    private int jour;
    private int heure;
    private int minute;
    private int seconde;
    private String nom;
    private String prenom;
    
    /**
     * Creates new form SupprimerArticle
     */
    public SupprimerArticle() {
        initComponents();
        dateHeure();
        article();
    }
    
    
    public SupprimerArticle(String adresseMail)
    {
        initComponents();
        this.mailAdress=adresseMail;
        textMarque.setVisible(false);
        textPrixUnit.setVisible(false);
        textPrixPack.setVisible(false);
        textQuantitePack.setVisible(false);
        textStock.setVisible(false);
        textDescription.setVisible(false);
        labelEuro1.setVisible(false);
        labelEuro2.setVisible(false);
        dateHeure();
        article();
        
    }
    
    public String getAdressMail()
    {
        return this.mailAdress;
    }
    
    
     Connection con;
     PreparedStatement pst;
     ResultSet rs;

    public void connexion() {
        try {
            //maconnexion= new Connexion("shopping","root","");
            Class.forName("com.mysql.cj.jdbc.Driver");

            //nameDatabase="shopping";  //nom de la database sur wampserveur
            String urlDatabase = "jdbc:mysql://localhost:3306/shopping";

            //création d'une connexion JDBC à la base 
            con = DriverManager.getConnection(urlDatabase,"root", "root");
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    public void article() {

                    try {
                        connexion();
                        String sqlSelectMarque = "SELECT marque from article";
                        pst = con.prepareStatement(sqlSelectMarque);
                        rs = pst.executeQuery();

                        while(rs.next()) {
                            comboBoxArticle.addItem(rs.getString("marque"));

                        }
                        con.close();

                    } catch (SQLException e) {
                        e.printStackTrace();
                    }            

    }
    
    
             // sous programme pour avoir la date actuelle et l'heure actuelle
    public void dateHeure() {
        Thread tr = new Thread() {
            @Override
            public void run() {
                for (;;) {
                    try {
                        Calendar calendrier = new GregorianCalendar();

                        annee = calendrier.get(Calendar.YEAR);
                        mois = calendrier.get(Calendar.MONTH);
                        jour = calendrier.get(Calendar.DAY_OF_MONTH);

                        heure = calendrier.get(Calendar.HOUR_OF_DAY);
                        minute = calendrier.get(Calendar.MINUTE);
                        seconde = calendrier.get(Calendar.SECOND);

                        mois = mois + 1;
                        textDate.setText(jour + "/" + mois + "/" + annee);
                        textHeure.setText(heure + ":" + minute + ":" + seconde);
                        sleep(1000);

                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }

        };
        tr.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textDate = new javax.swing.JLabel();
        textHeure = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonDeco = new javax.swing.JButton();
        comboBoxArticle = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textMarque = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textPrixUnit = new javax.swing.JLabel();
        labelEuro1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textPrixPack = new javax.swing.JLabel();
        labelEuro2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textQuantitePack = new javax.swing.JLabel();
        buttonValider = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        textStock = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textDescription = new javax.swing.JLabel();
        buttonSupprimer = new javax.swing.JButton();
        buttonRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabel1.setText("Supprimer un article");

        textDate.setText("DATE");

        textHeure.setText("HEURE");

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel2.setText("Sélectionnez l'article : ");

        buttonDeco.setBackground(new java.awt.Color(0, 0, 0));
        buttonDeco.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        buttonDeco.setForeground(new java.awt.Color(255, 255, 255));
        buttonDeco.setText("SE DECONNECTER");
        buttonDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecoActionPerformed(evt);
            }
        });

        comboBoxArticle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rechercher un article" }));

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel3.setText("Marque :");

        textMarque.setText("MARQUE");

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel5.setText("Prix Unitaire : ");

        textPrixUnit.setText("PRIX UNIT");

        labelEuro1.setText("€");

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel6.setText("Prix Pack :");

        textPrixPack.setText("PRIX PACK");

        labelEuro2.setText("€");

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel7.setText("Quantité Pack :");

        textQuantitePack.setText("QUANTITE PACK");

        buttonValider.setBackground(new java.awt.Color(0, 0, 0));
        buttonValider.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        buttonValider.setForeground(new java.awt.Color(255, 255, 255));
        buttonValider.setText("VALIDER");
        buttonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel10.setText("Stock :");

        textStock.setText("STOCK");

        jLabel12.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel12.setText("Description :");

        textDescription.setText("DESCRIPTION");

        buttonSupprimer.setBackground(new java.awt.Color(0, 0, 0));
        buttonSupprimer.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        buttonSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        buttonSupprimer.setText("SUPPRIMER");
        buttonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerActionPerformed(evt);
            }
        });

        buttonRetour.setBackground(new java.awt.Color(0, 0, 0));
        buttonRetour.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        buttonRetour.setForeground(new java.awt.Color(255, 255, 255));
        buttonRetour.setText("RETOUR");
        buttonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(comboBoxArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(buttonValider))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textHeure)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(7, 7, 7)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textQuantitePack, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textStock, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(textPrixUnit)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(labelEuro1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(textMarque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(textPrixPack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelEuro2)))))))
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(buttonRetour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSupprimer)
                .addGap(154, 154, 154)
                .addComponent(buttonDeco, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDate)
                            .addComponent(textHeure)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonValider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textMarque))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textPrixUnit)
                    .addComponent(labelEuro1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textPrixPack)
                    .addComponent(labelEuro2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textQuantitePack))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textStock)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDescription)
                    .addComponent(jLabel12))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSupprimer)
                    .addComponent(buttonRetour)
                    .addComponent(buttonDeco))
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderActionPerformed
        // TODO add your handling code here:
        
         try {
            connexion();
            String sqlSelectMarque = "SELECT marque,prix_unitaire,prix_pack,Quantite_pack,stock,description FROM article WHERE marque=?";
            pst = con.prepareStatement(sqlSelectMarque);
            pst.setString(1, comboBoxArticle.getSelectedItem().toString());
            rs = pst.executeQuery();

            while(rs.next()) {
                textMarque.setText(rs.getString("marque"));
                textMarque.setVisible(true);
                textPrixUnit.setText(rs.getString("prix_unitaire"));
                textPrixUnit.setVisible(true);
                labelEuro1.setVisible(true);
                textPrixPack.setText(rs.getString("prix_pack"));
                textPrixPack.setVisible(true);
                labelEuro2.setVisible(true);
                textQuantitePack.setText(rs.getString("Quantite_pack"));
                textQuantitePack.setVisible(true);
                textStock.setText(rs.getString("stock"));
                textStock.setVisible(true);
                textDescription.setText(rs.getString("description"));
                textDescription.setVisible(true);
            }
             con.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonValiderActionPerformed

    private void buttonDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecoActionPerformed
        // TODO add your handling code here:
        SupprimerArticle.super.dispose();
        connexion();

        Home homepage = new Home();
        homepage.setVisible(true);
    }//GEN-LAST:event_buttonDecoActionPerformed

    private void buttonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerActionPerformed
        // TODO add your handling code here:
        
        try {
            connexion();
            pst = con.prepareStatement("DELETE FROM article WHERE marque=?");
            
            pst.setString(1, comboBoxArticle.getSelectedItem().toString());
            pst.executeUpdate();
           // con.close();
            String messageTempo1 = "L'article " + comboBoxArticle.getSelectedItem().toString() + " a bien été supprimé.";
            JOptionPane.showMessageDialog(null, messageTempo1);

        } catch (HeadlessException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "La suppression a échoué: recommencez...");
        }    
    }//GEN-LAST:event_buttonSupprimerActionPerformed

    private void buttonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetourActionPerformed
        // TODO add your handling code here:
        SupprimerArticle.super.dispose();
        connexion();

        //PageEmpConnecte retourPageEmp = new PageEmpConnecte(getMailAdress());
        PageEmpConnecte retourPageEmp = new PageEmpConnecte(getAdressMail());
        retourPageEmp.setVisible(true);
    }//GEN-LAST:event_buttonRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupprimerArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupprimerArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupprimerArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupprimerArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupprimerArticle(getAdressMail()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeco;
    private javax.swing.JButton buttonRetour;
    private javax.swing.JButton buttonSupprimer;
    private javax.swing.JButton buttonValider;
    private javax.swing.JComboBox<String> comboBoxArticle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEuro1;
    private javax.swing.JLabel labelEuro2;
    private javax.swing.JLabel textDate;
    private javax.swing.JLabel textDescription;
    private javax.swing.JLabel textHeure;
    private javax.swing.JLabel textMarque;
    private javax.swing.JLabel textPrixPack;
    private javax.swing.JLabel textPrixUnit;
    private javax.swing.JLabel textQuantitePack;
    private javax.swing.JLabel textStock;
    // End of variables declaration//GEN-END:variables
}
